Num class
sreedhara-aneesh/csc510-fall22-hw-g33 pull request #3
Opened 2022-09-06 21:12 UTC by rpmertz

2022-09-09 03:52 UTC, sreedhara-aneesh commented on test/test_sym.py
> +test ()
Don't call your `test()` method in the file, the test engine will call it itself.

2022-09-09 03:52 UTC, sreedhara-aneesh commented on test/test_the.py
> +test ()
Don't call your `test()` method in the file, the test engine will call it itself.

2022-09-09 03:59 UTC, sreedhara-aneesh requested changes
Don't call test methods within the test files, the test methods will be called by the test engine itself. Left comments where this needs to be addressed. While this is fine for now since all tests are passing anyways, if there are any failing tests it will mess up the test engine.

2022-09-13 06:25 UTC, mkudith approved these changes
looks good to me

2022-09-15 14:42 UTC, sreedhara-aneesh approved these changes

2022-09-20 23:10 UTC, merged